### ISSUE TITLE
[Query] Public Key of Curve25519 is compatible with Ed25519

### ISSUE THREAD

**Issue by vzool** [lt/PHP-Curve25519#5]
Hi,

I'm wondering if Curve25519 keys are compatible with Ed25519(Signing & Authenticating)?

Thanks

**Comment by lt** [comment]
Not without conversion.

Curve25519 public keys are 255-bit values on the x axis while Ed25519 public keys are 255-bit values on the y axis with an additional sign bit.

You can convert by performing `y = ((x - 1) / ( x + 1)) % (2 ** 255) - 19`

**Comment by vzool** [comment]
Aha, nice ...

So, the complete solution for that is like this:

`y[0 .. 255] = ((x[0 .. 255] - 1) / (x[0 .. 255] + 1)) % ((2 ** 255) - 19)`

Right?
